import HomeScreen from '@screens/Home'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sapo Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen />
    </div>
  )
}
